"""Release-chain specs for v2.5.0 through v3.0.0."""

from __future__ import annotations

from typing import Any


RELEASE_SPECS: list[dict[str, Any]] = [
    {
        "key": "v25",
        "package_dir": "equity_v25_quality_closeout",
        "target_version": "v2.5.0-a-share-simulation-research-quality-closeout-and-full-regression",
        "source_version": "v2.4.0-a-share-simulation-research-maintenance-quality-and-artifact-bloat-reduction",
        "recommended_next_version": "v2.6.0-a-share-public-data-provider-adapter-and-data-contract-hardening",
        "result_name": "v25_quality_closeout_result",
        "manifest_name": "v25_quality_closeout_manifest",
        "audit_json": "a_share_v25_quality_closeout_audit.json",
        "audit_md": "A_SHARE_V25_QUALITY_CLOSEOUT_AUDIT.md",
        "build_command": "build-a-share-v25-quality-closeout",
        "audit_command": "audit-a-share-v25-quality-closeout",
        "all_command": "build-and-audit-a-share-v25-quality-closeout",
        "component_commands": [
            "build-a-share-v25-full-regression-evidence",
            "build-a-share-v25-safety-regression-sweep",
            "build-a-share-v25-owner-quality-dashboard",
        ],
        "json_names": [
            "v25_quality_closeout_request",
            "v25_full_regression_evidence",
            "v25_v23_v24_carry_forward_closeout",
            "v25_artifact_report_journal_closeout",
            "v25_safety_regression_sweep",
            "v25_cli_contract_closeout",
            "v25_owner_quality_dashboard_result",
            "v25_artifact_integrity_sweep",
            "v25_protected_path_sweep",
            "v25_safety_boundary_sweep",
            "v25_quality_closeout_result",
            "v25_quality_closeout_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V25_FULL_REGRESSION_REPORT.md",
            "A_SHARE_V25_V23_V24_CARRY_FORWARD_CLOSEOUT.md",
            "A_SHARE_V25_ARTIFACT_REPORT_JOURNAL_CLOSEOUT.md",
            "A_SHARE_V25_SAFETY_REGRESSION_SWEEP.md",
            "A_SHARE_V25_CLI_CONTRACT_CLOSEOUT.md",
            "A_SHARE_V25_OWNER_QUALITY_DASHBOARD.md",
            "A_SHARE_V25_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v24_baseline_verified",
            "v23_v24_no_full_pytest_carried_forward",
            "full_regression_evidence_generated",
            "artifact_report_journal_closeout_generated",
            "safety_regression_sweep_generated",
            "cli_contract_closeout_generated",
            "owner_quality_dashboard_generated",
            "full_pytest_run",
            "full_pytest_passed",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
        ],
        "required_false": [
            "fabricated_test_result",
            "fabricated_audit_result",
            "fabricated_release_evidence",
            "historical_evidence_deleted",
            "audit_evidence_deleted",
            "release_evidence_deleted",
        ],
        "full_pytest_required": True,
        "source_result_dir": "equity_v24_maintenance_quality",
        "source_result_name": "v24_maintenance_quality_result",
        "source_audit_json": "a_share_v24_maintenance_quality_audit.json",
    },
    {
        "key": "v26",
        "package_dir": "equity_v26_public_data_provider",
        "target_version": "v2.6.0-a-share-public-data-provider-adapter-and-data-contract-hardening",
        "source_version": "v2.5.0-a-share-simulation-research-quality-closeout-and-full-regression",
        "recommended_next_version": "v2.7.0-a-share-simulated-strategy-lifecycle-and-canary-governance-hardening",
        "result_name": "v26_public_data_provider_result",
        "manifest_name": "v26_public_data_provider_manifest",
        "audit_json": "a_share_v26_public_data_provider_audit.json",
        "audit_md": "A_SHARE_V26_PUBLIC_DATA_PROVIDER_AUDIT.md",
        "build_command": "build-a-share-v26-public-data-provider",
        "audit_command": "audit-a-share-v26-public-data-provider",
        "all_command": "build-and-audit-a-share-v26-public-data-provider",
        "component_commands": [
            "build-a-share-provider-contract-review",
            "build-a-share-provider-health-review",
            "build-a-share-data-contract-normalization-review",
            "build-a-share-provider-comparison-review",
            "build-a-share-provider-refresh-dry-run",
            "build-a-share-owner-provider-dashboard",
        ],
        "json_names": [
            "v26_public_data_provider_request",
            "v26_provider_adapter_registry",
            "v26_provider_health_result",
            "v26_data_contract_normalization_result",
            "v26_provider_comparison_result",
            "v26_provider_refresh_dry_run_result",
            "v26_import_plan_result",
            "v26_owner_provider_dashboard_result",
            "v26_artifact_integrity_sweep",
            "v26_protected_path_sweep",
            "v26_safety_boundary_sweep",
            "v26_public_data_provider_result",
            "v26_public_data_provider_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V26_PROVIDER_ADAPTER_CONTRACT_REPORT.md",
            "A_SHARE_V26_PROVIDER_HEALTH_REPORT.md",
            "A_SHARE_V26_DATA_CONTRACT_NORMALIZATION_REPORT.md",
            "A_SHARE_V26_PROVIDER_COMPARISON_REPORT.md",
            "A_SHARE_V26_REFRESH_DRY_RUN_AND_IMPORT_PLAN.md",
            "A_SHARE_V26_OWNER_PROVIDER_DASHBOARD.md",
            "A_SHARE_V26_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v25_baseline_verified",
            "provider_adapter_registry_generated",
            "provider_health_result_generated",
            "data_contract_normalization_result_generated",
            "provider_comparison_result_generated",
            "provider_refresh_dry_run_result_generated",
            "import_plan_result_generated",
            "owner_provider_dashboard_generated",
            "refresh_dry_run_only",
            "targeted_pytest_required",
        ],
        "required_false": [
            "broker_adapter_added",
            "private_account_adapter_added",
            "real_order_adapter_added",
            "order_preview_adapter_added",
            "fabricated_provider_availability",
            "fabricated_provider_data",
            "fabricated_schema_normalization",
            "unsafe_import_performed",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "source_result_dir": "equity_v25_quality_closeout",
        "source_result_name": "v25_quality_closeout_result",
        "source_audit_json": "a_share_v25_quality_closeout_audit.json",
    },
    {
        "key": "v27",
        "package_dir": "equity_v27_simulated_strategy_lifecycle",
        "target_version": "v2.7.0-a-share-simulated-strategy-lifecycle-and-canary-governance-hardening",
        "source_version": "v2.6.0-a-share-public-data-provider-adapter-and-data-contract-hardening",
        "recommended_next_version": "v2.8.0-a-share-autonomous-research-experiment-engine-and-llm-rl-governance-hardening",
        "result_name": "v27_strategy_lifecycle_result",
        "manifest_name": "v27_strategy_lifecycle_manifest",
        "audit_json": "a_share_v27_strategy_lifecycle_audit.json",
        "audit_md": "A_SHARE_V27_STRATEGY_LIFECYCLE_AUDIT.md",
        "build_command": "build-a-share-v27-strategy-lifecycle",
        "audit_command": "audit-a-share-v27-strategy-lifecycle",
        "all_command": "build-and-audit-a-share-v27-strategy-lifecycle",
        "component_commands": [
            "build-a-share-simulated-canary-governance",
            "build-a-share-strategy-transition-evidence",
            "build-a-share-simulation-active-strategy-registry",
            "build-a-share-owner-strategy-lifecycle-dashboard",
        ],
        "json_names": [
            "v27_strategy_lifecycle_request",
            "v27_strategy_lifecycle_registry",
            "v27_virtual_canary_governance_result",
            "v27_transition_evidence_result",
            "v27_simulation_active_strategy_registry",
            "v27_lifecycle_monitoring_alerts",
            "v27_owner_lifecycle_dashboard_result",
            "v27_artifact_integrity_sweep",
            "v27_protected_path_sweep",
            "v27_safety_boundary_sweep",
            "v27_strategy_lifecycle_result",
            "v27_strategy_lifecycle_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V27_STRATEGY_LIFECYCLE_REPORT.md",
            "A_SHARE_V27_VIRTUAL_CANARY_GOVERNANCE_REPORT.md",
            "A_SHARE_V27_TRANSITION_EVIDENCE_REPORT.md",
            "A_SHARE_V27_SIMULATION_ACTIVE_STRATEGY_REGISTRY.md",
            "A_SHARE_V27_OWNER_LIFECYCLE_DASHBOARD.md",
            "A_SHARE_V27_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v26_baseline_verified",
            "strategy_lifecycle_registry_generated",
            "virtual_canary_governance_result_generated",
            "transition_evidence_result_generated",
            "simulation_active_strategy_registry_generated",
            "owner_lifecycle_dashboard_generated",
        ],
        "required_false": [
            "real_trading_active_state_present",
            "real_canary_state_present",
            "broker_active_state_present",
            "transition_evidence_fabricated",
            "canary_evidence_fabricated",
            "promotion_generates_real_trade",
            "demotion_generates_sell_signal",
            "rollback_generates_real_trade",
            "simulation_active_generates_real_order",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "source_result_dir": "equity_v26_public_data_provider",
        "source_result_name": "v26_public_data_provider_result",
        "source_audit_json": "a_share_v26_public_data_provider_audit.json",
    },
    {
        "key": "v28",
        "package_dir": "equity_v28_autonomous_research_experiment",
        "target_version": "v2.8.0-a-share-autonomous-research-experiment-engine-and-llm-rl-governance-hardening",
        "source_version": "v2.7.0-a-share-simulated-strategy-lifecycle-and-canary-governance-hardening",
        "recommended_next_version": "v2.9.0-a-share-v3-readiness-docs-migration-and-release-candidate-prep",
        "result_name": "v28_autonomous_research_result",
        "manifest_name": "v28_autonomous_research_manifest",
        "audit_json": "a_share_v28_autonomous_research_audit.json",
        "audit_md": "A_SHARE_V28_AUTONOMOUS_RESEARCH_AUDIT.md",
        "build_command": "build-a-share-v28-autonomous-research-experiment",
        "audit_command": "audit-a-share-v28-autonomous-research-experiment",
        "all_command": "build-and-audit-a-share-v28-autonomous-research-experiment",
        "component_commands": [
            "build-a-share-llm-research-proposal-governance",
            "build-a-share-rl-policy-governance",
            "build-a-share-parameter-experiment-engine",
            "build-a-share-autonomous-research-queue",
            "build-a-share-owner-autonomous-research-dashboard",
        ],
        "json_names": [
            "v28_autonomous_research_request",
            "v28_experiment_registry_result",
            "v28_hypothesis_registry_result",
            "v28_llm_proposal_governance_result",
            "v28_rl_policy_governance_result",
            "v28_parameter_experiment_result",
            "v28_experiment_evaluation_scorecard",
            "v28_research_queue_result",
            "v28_owner_autonomous_research_dashboard_result",
            "v28_artifact_integrity_sweep",
            "v28_protected_path_sweep",
            "v28_safety_boundary_sweep",
            "v28_autonomous_research_result",
            "v28_autonomous_research_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V28_AUTONOMOUS_RESEARCH_OVERVIEW.md",
            "A_SHARE_V28_LLM_PROPOSAL_GOVERNANCE_REPORT.md",
            "A_SHARE_V28_RL_POLICY_GOVERNANCE_REPORT.md",
            "A_SHARE_V28_PARAMETER_EXPERIMENT_REPORT.md",
            "A_SHARE_V28_EXPERIMENT_EVALUATION_REPORT.md",
            "A_SHARE_V28_RESEARCH_QUEUE_REPORT.md",
            "A_SHARE_V28_OWNER_AUTONOMOUS_RESEARCH_DASHBOARD.md",
            "A_SHARE_V28_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v27_baseline_verified",
            "experiment_registry_generated",
            "hypothesis_registry_generated",
            "llm_proposal_governance_generated",
            "rl_policy_governance_generated",
            "parameter_experiment_result_generated",
            "experiment_evaluation_scorecard_generated",
            "research_queue_generated",
            "owner_autonomous_research_dashboard_generated",
        ],
        "required_false": [
            "llm_proposal_fabricated",
            "rl_policy_result_fabricated",
            "experiment_result_fabricated",
            "statistical_claim_fabricated",
            "llm_proposal_generates_trade_instruction",
            "rl_policy_controls_real_account",
            "parameter_engine_modifies_active_strategy",
            "experiment_decision_deploys_live",
            "research_queue_installs_scheduler",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "source_result_dir": "equity_v27_simulated_strategy_lifecycle",
        "source_result_name": "v27_strategy_lifecycle_result",
        "source_audit_json": "a_share_v27_strategy_lifecycle_audit.json",
    },
    {
        "key": "v29",
        "package_dir": "equity_v29_v3_readiness",
        "target_version": "v2.9.0-a-share-v3-readiness-docs-migration-and-release-candidate-prep",
        "source_version": "v2.8.0-a-share-autonomous-research-experiment-engine-and-llm-rl-governance-hardening",
        "recommended_next_version": "v3.0.0-a-share-autonomous-simulation-research-platform-final-closeout",
        "result_name": "v29_v3_readiness_result",
        "manifest_name": "v29_v3_readiness_manifest",
        "audit_json": "a_share_v29_v3_readiness_audit.json",
        "audit_md": "A_SHARE_V29_V3_READINESS_AUDIT.md",
        "build_command": "build-a-share-v29-v3-readiness",
        "audit_command": "audit-a-share-v29-v3-readiness",
        "all_command": "build-and-audit-a-share-v29-v3-readiness",
        "component_commands": [
            "build-a-share-v3-docs-guide",
            "build-a-share-v3-migration-plan",
            "build-a-share-v3-readiness-dashboard",
        ],
        "json_names": [
            "v29_v3_readiness_request",
            "v29_release_lineage_summary",
            "v29_docs_operator_guide_result",
            "v29_migration_upgrade_plan_result",
            "v29_v3_release_candidate_prerequisites",
            "v29_system_dependency_graph_result",
            "v29_known_limitations_risk_register",
            "v29_owner_v3_readiness_dashboard_result",
            "v29_artifact_integrity_sweep",
            "v29_protected_path_sweep",
            "v29_safety_boundary_sweep",
            "v29_v3_readiness_result",
            "v29_v3_readiness_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V29_V3_READINESS_OVERVIEW.md",
            "A_SHARE_V29_OPERATOR_AND_CLI_GUIDE.md",
            "A_SHARE_V29_MIGRATION_AND_UPGRADE_PLAN.md",
            "A_SHARE_V29_SYSTEM_DEPENDENCY_GRAPH.md",
            "A_SHARE_V29_KNOWN_LIMITATIONS_RISK_REGISTER.md",
            "A_SHARE_V29_OWNER_V3_READINESS_DASHBOARD.md",
            "A_SHARE_V29_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v28_baseline_verified",
            "release_lineage_summary_generated",
            "docs_operator_guide_generated",
            "migration_upgrade_plan_generated",
            "v3_release_candidate_prerequisites_generated",
            "system_dependency_graph_generated",
            "known_limitations_risk_register_generated",
            "owner_v3_readiness_dashboard_generated",
        ],
        "required_false": [
            "v3_released",
            "full_pytest_run",
            "docs_fabricated",
            "migration_result_fabricated",
            "dependency_graph_fabricated",
            "known_limitations_hidden",
        ],
        "full_pytest_required": False,
        "source_result_dir": "equity_v28_autonomous_research_experiment",
        "source_result_name": "v28_autonomous_research_result",
        "source_audit_json": "a_share_v28_autonomous_research_audit.json",
    },
    {
        "key": "v30",
        "package_dir": "equity_v30_final_closeout",
        "target_version": "v3.0.0-a-share-autonomous-simulation-research-platform-final-closeout",
        "source_version": "v2.9.0-a-share-v3-readiness-docs-migration-and-release-candidate-prep",
        "recommended_next_version": "v3.1.0-a-share-public-data-provider-integration-and-research-workflow-performance-hardening",
        "result_name": "v30_final_closeout_result",
        "manifest_name": "v30_final_closeout_manifest",
        "audit_json": "a_share_v30_final_closeout_audit.json",
        "audit_md": "A_SHARE_V30_FINAL_CLOSEOUT_AUDIT.md",
        "build_command": "build-a-share-v30-final-closeout",
        "audit_command": "audit-a-share-v30-final-closeout",
        "all_command": "build-and-audit-a-share-v30-final-closeout",
        "component_commands": [
            "build-a-share-v30-full-regression-evidence",
            "build-a-share-v30-final-safety-sweep",
            "build-a-share-v30-final-capability-map",
            "build-a-share-v30-owner-final-dashboard",
        ],
        "json_names": [
            "v30_final_closeout_request",
            "v30_v2_release_lineage_validation",
            "v30_full_regression_evidence",
            "v30_final_safety_boundary_sweep",
            "v30_release_evidence_validation",
            "v30_capability_map_final_validation",
            "v30_known_limitations_next_phase_result",
            "v30_owner_final_dashboard_result",
            "v30_release_health_report",
            "v30_artifact_integrity_sweep",
            "v30_protected_path_sweep",
            "v30_safety_boundary_sweep",
            "v30_final_closeout_result",
            "v30_final_closeout_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V30_FINAL_CLOSEOUT_REPORT.md",
            "A_SHARE_V30_FULL_REGRESSION_REPORT.md",
            "A_SHARE_V30_FINAL_SAFETY_BOUNDARY_SWEEP.md",
            "A_SHARE_V30_CAPABILITY_MAP_FINAL_VALIDATION.md",
            "A_SHARE_V30_KNOWN_LIMITATIONS_AND_NEXT_PHASE.md",
            "A_SHARE_V30_OWNER_FINAL_DASHBOARD.md",
            "A_SHARE_V30_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v29_baseline_verified",
            "v2_release_lineage_validation_generated",
            "full_regression_evidence_generated",
            "final_safety_boundary_sweep_generated",
            "release_evidence_validation_generated",
            "capability_map_final_validation_generated",
            "known_limitations_next_phase_generated",
            "owner_final_dashboard_generated",
            "release_health_report_generated",
            "full_pytest_run",
            "full_pytest_passed",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
        ],
        "required_false": [
            "fabricated_release_evidence",
            "fabricated_test_result",
            "fabricated_audit_result",
            "fabricated_capability_claim",
            "historical_evidence_deleted",
            "audit_evidence_deleted",
            "release_evidence_deleted",
            "live_trading_ready",
        ],
        "full_pytest_required": True,
        "release_decision": "released_as_research_only_simulation_platform",
        "source_result_dir": "equity_v29_v3_readiness",
        "source_result_name": "v29_v3_readiness_result",
        "source_audit_json": "a_share_v29_v3_readiness_audit.json",
    },
]


def spec_by_key(key: str) -> dict[str, Any]:
    for spec in RELEASE_SPECS:
        if spec["key"] == key:
            return spec
    raise KeyError(key)


def command_to_spec(command: str) -> tuple[dict[str, Any], str] | tuple[None, None]:
    for spec in RELEASE_SPECS:
        if command == spec["build_command"]:
            return spec, "build"
        if command == spec["audit_command"]:
            return spec, "audit"
        if command == spec["all_command"]:
            return spec, "all"
        if command in spec["component_commands"]:
            return spec, "component"
    return None, None
