"""Release-chain specs for v2.5.0 through v3.0.0."""

from __future__ import annotations

from typing import Any


RELEASE_SPECS: list[dict[str, Any]] = [
    {
        "key": "v25",
        "package_dir": "equity_v25_quality_closeout",
        "target_version": "v2.5.0-a-share-simulation-research-quality-closeout-and-full-regression",
        "source_version": "v2.4.0-a-share-simulation-research-maintenance-quality-and-artifact-bloat-reduction",
        "recommended_next_version": "v2.6.0-a-share-public-data-provider-adapter-and-data-contract-hardening",
        "result_name": "v25_quality_closeout_result",
        "manifest_name": "v25_quality_closeout_manifest",
        "audit_json": "a_share_v25_quality_closeout_audit.json",
        "audit_md": "A_SHARE_V25_QUALITY_CLOSEOUT_AUDIT.md",
        "build_command": "build-a-share-v25-quality-closeout",
        "audit_command": "audit-a-share-v25-quality-closeout",
        "all_command": "build-and-audit-a-share-v25-quality-closeout",
        "component_commands": [
            "build-a-share-v25-full-regression-evidence",
            "build-a-share-v25-safety-regression-sweep",
            "build-a-share-v25-owner-quality-dashboard",
        ],
        "json_names": [
            "v25_quality_closeout_request",
            "v25_full_regression_evidence",
            "v25_v23_v24_carry_forward_closeout",
            "v25_artifact_report_journal_closeout",
            "v25_safety_regression_sweep",
            "v25_cli_contract_closeout",
            "v25_owner_quality_dashboard_result",
            "v25_artifact_integrity_sweep",
            "v25_protected_path_sweep",
            "v25_safety_boundary_sweep",
            "v25_quality_closeout_result",
            "v25_quality_closeout_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V25_FULL_REGRESSION_REPORT.md",
            "A_SHARE_V25_V23_V24_CARRY_FORWARD_CLOSEOUT.md",
            "A_SHARE_V25_ARTIFACT_REPORT_JOURNAL_CLOSEOUT.md",
            "A_SHARE_V25_SAFETY_REGRESSION_SWEEP.md",
            "A_SHARE_V25_CLI_CONTRACT_CLOSEOUT.md",
            "A_SHARE_V25_OWNER_QUALITY_DASHBOARD.md",
            "A_SHARE_V25_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v24_baseline_verified",
            "v23_v24_no_full_pytest_carried_forward",
            "full_regression_evidence_generated",
            "artifact_report_journal_closeout_generated",
            "safety_regression_sweep_generated",
            "cli_contract_closeout_generated",
            "owner_quality_dashboard_generated",
            "full_pytest_run",
            "full_pytest_passed",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
        ],
        "required_false": [
            "fabricated_test_result",
            "fabricated_audit_result",
            "fabricated_release_evidence",
            "historical_evidence_deleted",
            "audit_evidence_deleted",
            "release_evidence_deleted",
        ],
        "full_pytest_required": True,
        "source_result_dir": "equity_v24_maintenance_quality",
        "source_result_name": "v24_maintenance_quality_result",
        "source_audit_json": "a_share_v24_maintenance_quality_audit.json",
    },
    {
        "key": "v26",
        "package_dir": "equity_v26_public_data_provider",
        "target_version": "v2.6.0-a-share-public-data-provider-adapter-and-data-contract-hardening",
        "source_version": "v2.5.0-a-share-simulation-research-quality-closeout-and-full-regression",
        "recommended_next_version": "v2.7.0-a-share-simulated-strategy-lifecycle-and-canary-governance-hardening",
        "result_name": "v26_public_data_provider_result",
        "manifest_name": "v26_public_data_provider_manifest",
        "audit_json": "a_share_v26_public_data_provider_audit.json",
        "audit_md": "A_SHARE_V26_PUBLIC_DATA_PROVIDER_AUDIT.md",
        "build_command": "build-a-share-v26-public-data-provider",
        "audit_command": "audit-a-share-v26-public-data-provider",
        "all_command": "build-and-audit-a-share-v26-public-data-provider",
        "component_commands": [
            "build-a-share-provider-contract-review",
            "build-a-share-provider-health-review",
            "build-a-share-data-contract-normalization-review",
            "build-a-share-provider-comparison-review",
            "build-a-share-provider-refresh-dry-run",
            "build-a-share-owner-provider-dashboard",
        ],
        "json_names": [
            "v26_public_data_provider_request",
            "v26_provider_adapter_registry",
            "v26_provider_health_result",
            "v26_data_contract_normalization_result",
            "v26_provider_comparison_result",
            "v26_provider_refresh_dry_run_result",
            "v26_import_plan_result",
            "v26_owner_provider_dashboard_result",
            "v26_artifact_integrity_sweep",
            "v26_protected_path_sweep",
            "v26_safety_boundary_sweep",
            "v26_public_data_provider_result",
            "v26_public_data_provider_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V26_PROVIDER_ADAPTER_CONTRACT_REPORT.md",
            "A_SHARE_V26_PROVIDER_HEALTH_REPORT.md",
            "A_SHARE_V26_DATA_CONTRACT_NORMALIZATION_REPORT.md",
            "A_SHARE_V26_PROVIDER_COMPARISON_REPORT.md",
            "A_SHARE_V26_REFRESH_DRY_RUN_AND_IMPORT_PLAN.md",
            "A_SHARE_V26_OWNER_PROVIDER_DASHBOARD.md",
            "A_SHARE_V26_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v25_baseline_verified",
            "provider_adapter_registry_generated",
            "provider_health_result_generated",
            "data_contract_normalization_result_generated",
            "provider_comparison_result_generated",
            "provider_refresh_dry_run_result_generated",
            "import_plan_result_generated",
            "owner_provider_dashboard_generated",
            "refresh_dry_run_only",
            "targeted_pytest_required",
        ],
        "required_false": [
            "broker_adapter_added",
            "private_account_adapter_added",
            "real_order_adapter_added",
            "order_preview_adapter_added",
            "fabricated_provider_availability",
            "fabricated_provider_data",
            "fabricated_schema_normalization",
            "unsafe_import_performed",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "source_result_dir": "equity_v25_quality_closeout",
        "source_result_name": "v25_quality_closeout_result",
        "source_audit_json": "a_share_v25_quality_closeout_audit.json",
    },
    {
        "key": "v27",
        "package_dir": "equity_v27_simulated_strategy_lifecycle",
        "target_version": "v2.7.0-a-share-simulated-strategy-lifecycle-and-canary-governance-hardening",
        "source_version": "v2.6.0-a-share-public-data-provider-adapter-and-data-contract-hardening",
        "recommended_next_version": "v2.8.0-a-share-autonomous-research-experiment-engine-and-llm-rl-governance-hardening",
        "result_name": "v27_strategy_lifecycle_result",
        "manifest_name": "v27_strategy_lifecycle_manifest",
        "audit_json": "a_share_v27_strategy_lifecycle_audit.json",
        "audit_md": "A_SHARE_V27_STRATEGY_LIFECYCLE_AUDIT.md",
        "build_command": "build-a-share-v27-strategy-lifecycle",
        "audit_command": "audit-a-share-v27-strategy-lifecycle",
        "all_command": "build-and-audit-a-share-v27-strategy-lifecycle",
        "component_commands": [
            "build-a-share-simulated-canary-governance",
            "build-a-share-strategy-transition-evidence",
            "build-a-share-simulation-active-strategy-registry",
            "build-a-share-owner-strategy-lifecycle-dashboard",
        ],
        "json_names": [
            "v27_strategy_lifecycle_request",
            "v27_strategy_lifecycle_registry",
            "v27_virtual_canary_governance_result",
            "v27_transition_evidence_result",
            "v27_simulation_active_strategy_registry",
            "v27_lifecycle_monitoring_alerts",
            "v27_owner_lifecycle_dashboard_result",
            "v27_artifact_integrity_sweep",
            "v27_protected_path_sweep",
            "v27_safety_boundary_sweep",
            "v27_strategy_lifecycle_result",
            "v27_strategy_lifecycle_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V27_STRATEGY_LIFECYCLE_REPORT.md",
            "A_SHARE_V27_VIRTUAL_CANARY_GOVERNANCE_REPORT.md",
            "A_SHARE_V27_TRANSITION_EVIDENCE_REPORT.md",
            "A_SHARE_V27_SIMULATION_ACTIVE_STRATEGY_REGISTRY.md",
            "A_SHARE_V27_OWNER_LIFECYCLE_DASHBOARD.md",
            "A_SHARE_V27_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v26_baseline_verified",
            "strategy_lifecycle_registry_generated",
            "virtual_canary_governance_result_generated",
            "transition_evidence_result_generated",
            "simulation_active_strategy_registry_generated",
            "owner_lifecycle_dashboard_generated",
        ],
        "required_false": [
            "real_trading_active_state_present",
            "real_canary_state_present",
            "broker_active_state_present",
            "transition_evidence_fabricated",
            "canary_evidence_fabricated",
            "promotion_generates_real_trade",
            "demotion_generates_sell_signal",
            "rollback_generates_real_trade",
            "simulation_active_generates_real_order",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "source_result_dir": "equity_v26_public_data_provider",
        "source_result_name": "v26_public_data_provider_result",
        "source_audit_json": "a_share_v26_public_data_provider_audit.json",
    },
    {
        "key": "v28",
        "package_dir": "equity_v28_autonomous_research_experiment",
        "target_version": "v2.8.0-a-share-autonomous-research-experiment-engine-and-llm-rl-governance-hardening",
        "source_version": "v2.7.0-a-share-simulated-strategy-lifecycle-and-canary-governance-hardening",
        "recommended_next_version": "v2.9.0-a-share-v3-readiness-docs-migration-and-release-candidate-prep",
        "result_name": "v28_autonomous_research_result",
        "manifest_name": "v28_autonomous_research_manifest",
        "audit_json": "a_share_v28_autonomous_research_audit.json",
        "audit_md": "A_SHARE_V28_AUTONOMOUS_RESEARCH_AUDIT.md",
        "build_command": "build-a-share-v28-autonomous-research-experiment",
        "audit_command": "audit-a-share-v28-autonomous-research-experiment",
        "all_command": "build-and-audit-a-share-v28-autonomous-research-experiment",
        "component_commands": [
            "build-a-share-llm-research-proposal-governance",
            "build-a-share-rl-policy-governance",
            "build-a-share-parameter-experiment-engine",
            "build-a-share-autonomous-research-queue",
            "build-a-share-owner-autonomous-research-dashboard",
        ],
        "json_names": [
            "v28_autonomous_research_request",
            "v28_experiment_registry_result",
            "v28_hypothesis_registry_result",
            "v28_llm_proposal_governance_result",
            "v28_rl_policy_governance_result",
            "v28_parameter_experiment_result",
            "v28_experiment_evaluation_scorecard",
            "v28_research_queue_result",
            "v28_owner_autonomous_research_dashboard_result",
            "v28_artifact_integrity_sweep",
            "v28_protected_path_sweep",
            "v28_safety_boundary_sweep",
            "v28_autonomous_research_result",
            "v28_autonomous_research_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V28_AUTONOMOUS_RESEARCH_OVERVIEW.md",
            "A_SHARE_V28_LLM_PROPOSAL_GOVERNANCE_REPORT.md",
            "A_SHARE_V28_RL_POLICY_GOVERNANCE_REPORT.md",
            "A_SHARE_V28_PARAMETER_EXPERIMENT_REPORT.md",
            "A_SHARE_V28_EXPERIMENT_EVALUATION_REPORT.md",
            "A_SHARE_V28_RESEARCH_QUEUE_REPORT.md",
            "A_SHARE_V28_OWNER_AUTONOMOUS_RESEARCH_DASHBOARD.md",
            "A_SHARE_V28_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v27_baseline_verified",
            "experiment_registry_generated",
            "hypothesis_registry_generated",
            "llm_proposal_governance_generated",
            "rl_policy_governance_generated",
            "parameter_experiment_result_generated",
            "experiment_evaluation_scorecard_generated",
            "research_queue_generated",
            "owner_autonomous_research_dashboard_generated",
        ],
        "required_false": [
            "llm_proposal_fabricated",
            "rl_policy_result_fabricated",
            "experiment_result_fabricated",
            "statistical_claim_fabricated",
            "llm_proposal_generates_trade_instruction",
            "rl_policy_controls_real_account",
            "parameter_engine_modifies_active_strategy",
            "experiment_decision_deploys_live",
            "research_queue_installs_scheduler",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "source_result_dir": "equity_v27_simulated_strategy_lifecycle",
        "source_result_name": "v27_strategy_lifecycle_result",
        "source_audit_json": "a_share_v27_strategy_lifecycle_audit.json",
    },
    {
        "key": "v29",
        "package_dir": "equity_v29_v3_readiness",
        "target_version": "v2.9.0-a-share-v3-readiness-docs-migration-and-release-candidate-prep",
        "source_version": "v2.8.0-a-share-autonomous-research-experiment-engine-and-llm-rl-governance-hardening",
        "recommended_next_version": "v3.0.0-a-share-autonomous-simulation-research-platform-final-closeout",
        "result_name": "v29_v3_readiness_result",
        "manifest_name": "v29_v3_readiness_manifest",
        "audit_json": "a_share_v29_v3_readiness_audit.json",
        "audit_md": "A_SHARE_V29_V3_READINESS_AUDIT.md",
        "build_command": "build-a-share-v29-v3-readiness",
        "audit_command": "audit-a-share-v29-v3-readiness",
        "all_command": "build-and-audit-a-share-v29-v3-readiness",
        "component_commands": [
            "build-a-share-v3-docs-guide",
            "build-a-share-v3-migration-plan",
            "build-a-share-v3-readiness-dashboard",
        ],
        "json_names": [
            "v29_v3_readiness_request",
            "v29_release_lineage_summary",
            "v29_docs_operator_guide_result",
            "v29_migration_upgrade_plan_result",
            "v29_v3_release_candidate_prerequisites",
            "v29_system_dependency_graph_result",
            "v29_known_limitations_risk_register",
            "v29_owner_v3_readiness_dashboard_result",
            "v29_artifact_integrity_sweep",
            "v29_protected_path_sweep",
            "v29_safety_boundary_sweep",
            "v29_v3_readiness_result",
            "v29_v3_readiness_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V29_V3_READINESS_OVERVIEW.md",
            "A_SHARE_V29_OPERATOR_AND_CLI_GUIDE.md",
            "A_SHARE_V29_MIGRATION_AND_UPGRADE_PLAN.md",
            "A_SHARE_V29_SYSTEM_DEPENDENCY_GRAPH.md",
            "A_SHARE_V29_KNOWN_LIMITATIONS_RISK_REGISTER.md",
            "A_SHARE_V29_OWNER_V3_READINESS_DASHBOARD.md",
            "A_SHARE_V29_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v28_baseline_verified",
            "release_lineage_summary_generated",
            "docs_operator_guide_generated",
            "migration_upgrade_plan_generated",
            "v3_release_candidate_prerequisites_generated",
            "system_dependency_graph_generated",
            "known_limitations_risk_register_generated",
            "owner_v3_readiness_dashboard_generated",
        ],
        "required_false": [
            "v3_released",
            "full_pytest_run",
            "docs_fabricated",
            "migration_result_fabricated",
            "dependency_graph_fabricated",
            "known_limitations_hidden",
        ],
        "full_pytest_required": False,
        "source_result_dir": "equity_v28_autonomous_research_experiment",
        "source_result_name": "v28_autonomous_research_result",
        "source_audit_json": "a_share_v28_autonomous_research_audit.json",
    },
    {
        "key": "v30",
        "package_dir": "equity_v30_final_closeout",
        "target_version": "v3.0.0-a-share-autonomous-simulation-research-platform-final-closeout",
        "source_version": "v2.9.0-a-share-v3-readiness-docs-migration-and-release-candidate-prep",
        "recommended_next_version": "v3.1.0-a-share-public-data-provider-integration-and-research-workflow-performance-hardening",
        "result_name": "v30_final_closeout_result",
        "manifest_name": "v30_final_closeout_manifest",
        "audit_json": "a_share_v30_final_closeout_audit.json",
        "audit_md": "A_SHARE_V30_FINAL_CLOSEOUT_AUDIT.md",
        "build_command": "build-a-share-v30-final-closeout",
        "audit_command": "audit-a-share-v30-final-closeout",
        "all_command": "build-and-audit-a-share-v30-final-closeout",
        "component_commands": [
            "build-a-share-v30-full-regression-evidence",
            "build-a-share-v30-final-safety-sweep",
            "build-a-share-v30-final-capability-map",
            "build-a-share-v30-owner-final-dashboard",
        ],
        "json_names": [
            "v30_final_closeout_request",
            "v30_v2_release_lineage_validation",
            "v30_full_regression_evidence",
            "v30_final_safety_boundary_sweep",
            "v30_release_evidence_validation",
            "v30_capability_map_final_validation",
            "v30_known_limitations_next_phase_result",
            "v30_owner_final_dashboard_result",
            "v30_release_health_report",
            "v30_artifact_integrity_sweep",
            "v30_protected_path_sweep",
            "v30_safety_boundary_sweep",
            "v30_final_closeout_result",
            "v30_final_closeout_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V30_FINAL_CLOSEOUT_REPORT.md",
            "A_SHARE_V30_FULL_REGRESSION_REPORT.md",
            "A_SHARE_V30_FINAL_SAFETY_BOUNDARY_SWEEP.md",
            "A_SHARE_V30_CAPABILITY_MAP_FINAL_VALIDATION.md",
            "A_SHARE_V30_KNOWN_LIMITATIONS_AND_NEXT_PHASE.md",
            "A_SHARE_V30_OWNER_FINAL_DASHBOARD.md",
            "A_SHARE_V30_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v29_baseline_verified",
            "v2_release_lineage_validation_generated",
            "full_regression_evidence_generated",
            "final_safety_boundary_sweep_generated",
            "release_evidence_validation_generated",
            "capability_map_final_validation_generated",
            "known_limitations_next_phase_generated",
            "owner_final_dashboard_generated",
            "release_health_report_generated",
            "full_pytest_run",
            "full_pytest_passed",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
        ],
        "required_false": [
            "fabricated_release_evidence",
            "fabricated_test_result",
            "fabricated_audit_result",
            "fabricated_capability_claim",
            "historical_evidence_deleted",
            "audit_evidence_deleted",
            "release_evidence_deleted",
            "live_trading_ready",
        ],
        "full_pytest_required": True,
        "release_decision": "released_as_research_only_simulation_platform",
        "source_result_dir": "equity_v29_v3_readiness",
        "source_result_name": "v29_v3_readiness_result",
        "source_audit_json": "a_share_v29_v3_readiness_audit.json",
    },
    {
        "key": "v32",
        "package_dir": "equity_v32_workflow_performance",
        "target_version": "v3.2.0-a-share-research-workflow-performance-caching-and-incremental-build-hardening",
        "source_version": "v3.1.0-a-share-post-v3-verification-reproducibility-and-external-audit-readiness-hardening",
        "recommended_next_version": "v3.3.0-a-share-owner-knowledge-base-report-query-and-evidence-router-hardening",
        "result_name": "v32_workflow_performance_result",
        "manifest_name": "v32_workflow_performance_manifest",
        "audit_json": "a_share_v32_workflow_performance_audit.json",
        "audit_md": "A_SHARE_V32_WORKFLOW_PERFORMANCE_AUDIT.md",
        "build_command": "build-a-share-v32-workflow-performance",
        "audit_command": "audit-a-share-v32-workflow-performance",
        "all_command": "build-and-audit-a-share-v32-workflow-performance",
        "component_commands": [
            "build-a-share-incremental-build-plan",
            "build-a-share-cache-manifest-review",
            "build-a-share-performance-dashboard",
        ],
        "json_names": [
            "v32_workflow_performance_request",
            "v32_workflow_dependency_graph",
            "v32_cache_manifest_result",
            "v32_partial_rebuild_plan_result",
            "v32_runtime_profile_result",
            "v32_cache_correctness_audit_result",
            "v32_owner_performance_dashboard_result",
            "v32_artifact_integrity_sweep",
            "v32_protected_path_sweep",
            "v32_safety_boundary_sweep",
            "v32_workflow_performance_result",
            "v32_workflow_performance_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V32_WORKFLOW_PERFORMANCE_OVERVIEW.md",
            "A_SHARE_V32_INCREMENTAL_BUILD_PLAN.md",
            "A_SHARE_V32_CACHE_MANIFEST_REVIEW.md",
            "A_SHARE_V32_RUNTIME_PROFILE_REPORT.md",
            "A_SHARE_V32_CACHE_CORRECTNESS_AUDIT.md",
            "A_SHARE_V32_OWNER_PERFORMANCE_DASHBOARD.md",
            "A_SHARE_V32_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v31_baseline_verified",
            "workflow_dependency_graph_generated",
            "cache_manifest_result_generated",
            "partial_rebuild_plan_result_generated",
            "runtime_profile_result_generated",
            "cache_correctness_audit_result_generated",
            "owner_performance_dashboard_generated",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
            "targeted_pytest_required",
        ],
        "required_false": [
            "semantic_outputs_changed",
            "cache_reused_stale_artifact",
            "cache_bypassed_safety_audit",
            "cache_bypassed_protected_path_sweep",
            "cache_bypassed_artifact_integrity_sweep",
            "cache_result_fabricated",
            "runtime_profile_fabricated",
            "performance_claim_fabricated",
            "performance_score_is_owner_readiness_score",
            "performance_pass_means_live_trading_ready",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "full_pytest_deferred_until": "next-major-closeout-or-explicit-request",
        "warnings": [],
        "source_result_dir": "equity_v31_post_v3_verification",
        "source_result_name": "v31_post_v3_verification_result",
        "source_audit_json": "a_share_v31_post_v3_verification_audit.json",
    },
    {
        "key": "v33",
        "package_dir": "equity_v33_owner_knowledge_base",
        "target_version": "v3.3.0-a-share-owner-knowledge-base-report-query-and-evidence-router-hardening",
        "source_version": "v3.2.0-a-share-research-workflow-performance-caching-and-incremental-build-hardening",
        "recommended_next_version": "v3.4.0-a-share-simulation-portfolio-analytics-depth-and-risk-attribution-hardening",
        "result_name": "v33_owner_knowledge_base_result",
        "manifest_name": "v33_owner_knowledge_base_manifest",
        "audit_json": "a_share_v33_owner_knowledge_base_audit.json",
        "audit_md": "A_SHARE_V33_OWNER_KNOWLEDGE_BASE_AUDIT.md",
        "build_command": "build-a-share-v33-owner-knowledge-base",
        "audit_command": "audit-a-share-v33-owner-knowledge-base",
        "all_command": "build-and-audit-a-share-v33-owner-knowledge-base",
        "component_commands": [
            "build-a-share-report-query-index",
            "build-a-share-evidence-router",
            "build-a-share-owner-question-router",
            "build-a-share-decision-journal-query-index",
        ],
        "json_names": [
            "v33_owner_knowledge_base_request",
            "v33_report_query_index_result",
            "v33_evidence_router_result",
            "v33_owner_question_router_result",
            "v33_warning_blocker_limitation_search_result",
            "v33_decision_journal_query_result",
            "v33_owner_knowledge_dashboard_result",
            "v33_artifact_integrity_sweep",
            "v33_protected_path_sweep",
            "v33_safety_boundary_sweep",
            "v33_owner_knowledge_base_result",
            "v33_owner_knowledge_base_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V33_OWNER_KNOWLEDGE_BASE_OVERVIEW.md",
            "A_SHARE_V33_REPORT_QUERY_INDEX.md",
            "A_SHARE_V33_EVIDENCE_ROUTER_REPORT.md",
            "A_SHARE_V33_OWNER_QUESTION_ROUTER_REPORT.md",
            "A_SHARE_V33_WARNING_BLOCKER_LIMITATION_SEARCH.md",
            "A_SHARE_V33_DECISION_JOURNAL_QUERY_REPORT.md",
            "A_SHARE_V33_OWNER_KNOWLEDGE_DASHBOARD.md",
            "A_SHARE_V33_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v32_baseline_verified",
            "report_query_index_generated",
            "evidence_router_generated",
            "owner_question_router_generated",
            "warning_blocker_limitation_search_generated",
            "decision_journal_query_generated",
            "owner_knowledge_dashboard_generated",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
            "targeted_pytest_required",
        ],
        "required_false": [
            "knowledge_base_fabricated",
            "evidence_links_fabricated",
            "report_links_fabricated",
            "question_router_generates_trading_advice",
            "question_router_generates_buy_sell_signal",
            "question_router_generates_real_allocation",
            "decision_journal_query_generates_trade_instruction",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "full_pytest_deferred_until": "next-major-closeout-or-explicit-request",
        "warnings": [],
        "source_result_dir": "equity_v32_workflow_performance",
        "source_result_name": "v32_workflow_performance_result",
        "source_audit_json": "a_share_v32_workflow_performance_audit.json",
    },
    {
        "key": "v34",
        "package_dir": "equity_v34_portfolio_attribution",
        "target_version": "v3.4.0-a-share-simulation-portfolio-analytics-depth-and-risk-attribution-hardening",
        "source_version": "v3.3.0-a-share-owner-knowledge-base-report-query-and-evidence-router-hardening",
        "recommended_next_version": "v3.5.0-a-share-v3x-quality-closeout-long-horizon-regression-and-external-review-refresh",
        "result_name": "v34_portfolio_attribution_result",
        "manifest_name": "v34_portfolio_attribution_manifest",
        "audit_json": "a_share_v34_portfolio_attribution_audit.json",
        "audit_md": "A_SHARE_V34_PORTFOLIO_ATTRIBUTION_AUDIT.md",
        "build_command": "build-a-share-v34-portfolio-attribution",
        "audit_command": "audit-a-share-v34-portfolio-attribution",
        "all_command": "build-and-audit-a-share-v34-portfolio-attribution",
        "component_commands": [
            "build-a-share-nav-decomposition",
            "build-a-share-drawdown-attribution",
            "build-a-share-cost-slippage-attribution",
            "build-a-share-factor-sector-attribution",
            "build-a-share-owner-risk-attribution-dashboard",
        ],
        "json_names": [
            "v34_portfolio_attribution_request",
            "v34_nav_return_decomposition_result",
            "v34_drawdown_attribution_result",
            "v34_turnover_cost_slippage_attribution_result",
            "v34_factor_sector_industry_attribution_result",
            "v34_strategy_model_ensemble_contribution_result",
            "v34_owner_risk_attribution_dashboard_result",
            "v34_artifact_integrity_sweep",
            "v34_protected_path_sweep",
            "v34_safety_boundary_sweep",
            "v34_portfolio_attribution_result",
            "v34_portfolio_attribution_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V34_PORTFOLIO_ATTRIBUTION_OVERVIEW.md",
            "A_SHARE_V34_NAV_RETURN_DECOMPOSITION.md",
            "A_SHARE_V34_DRAWDOWN_ATTRIBUTION.md",
            "A_SHARE_V34_TURNOVER_COST_SLIPPAGE_ATTRIBUTION.md",
            "A_SHARE_V34_FACTOR_SECTOR_INDUSTRY_ATTRIBUTION.md",
            "A_SHARE_V34_STRATEGY_MODEL_ENSEMBLE_CONTRIBUTION.md",
            "A_SHARE_V34_OWNER_RISK_ATTRIBUTION_DASHBOARD.md",
            "A_SHARE_V34_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v33_baseline_verified",
            "nav_return_decomposition_generated",
            "drawdown_attribution_generated",
            "turnover_cost_slippage_attribution_generated",
            "factor_sector_industry_attribution_generated",
            "strategy_model_ensemble_contribution_generated",
            "owner_risk_attribution_dashboard_generated",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
            "targeted_pytest_required",
        ],
        "required_false": [
            "nav_attribution_fabricated",
            "drawdown_attribution_fabricated",
            "cost_slippage_attribution_fabricated",
            "factor_attribution_fabricated",
            "strategy_model_ensemble_contribution_fabricated",
            "attribution_generates_real_allocation",
            "attribution_generates_rebalance_advice",
            "attribution_generates_buy_sell_signal",
            "portfolio_is_real_portfolio",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "full_pytest_deferred_until": "next-major-closeout-or-explicit-request",
        "warnings": [],
        "source_result_dir": "equity_v33_owner_knowledge_base",
        "source_result_name": "v33_owner_knowledge_base_result",
        "source_audit_json": "a_share_v33_owner_knowledge_base_audit.json",
    },
    {
        "key": "v35",
        "package_dir": "equity_v35_v3x_quality_closeout",
        "target_version": "v3.5.0-a-share-v3x-quality-closeout-long-horizon-regression-and-external-review-refresh",
        "source_version": "v3.4.0-a-share-simulation-portfolio-analytics-depth-and-risk-attribution-hardening",
        "recommended_next_version": "v3.6.0-a-share-research-platform-knowledge-performance-and-attribution-maintenance",
        "result_name": "v35_v3x_quality_closeout_result",
        "manifest_name": "v35_v3x_quality_closeout_manifest",
        "audit_json": "a_share_v35_v3x_quality_closeout_audit.json",
        "audit_md": "A_SHARE_V35_V3X_QUALITY_CLOSEOUT_AUDIT.md",
        "build_command": "build-a-share-v35-v3x-quality-closeout",
        "audit_command": "audit-a-share-v35-v3x-quality-closeout",
        "all_command": "build-and-audit-a-share-v35-v3x-quality-closeout",
        "component_commands": [
            "build-a-share-v35-long-horizon-regression",
            "build-a-share-v35-capability-validation",
            "build-a-share-v35-external-review-refresh",
            "build-a-share-v35-owner-final-dashboard",
        ],
        "json_names": [
            "v35_v3x_quality_closeout_request",
            "v35_v3x_release_lineage_registry",
            "v35_long_horizon_regression_evidence",
            "v35_v3x_capability_validation_result",
            "v35_external_review_package_refresh_result",
            "v35_known_limitations_refresh_result",
            "v35_owner_final_v3x_dashboard_result",
            "v35_release_health_report",
            "v35_artifact_integrity_sweep",
            "v35_protected_path_sweep",
            "v35_safety_boundary_sweep",
            "v35_v3x_quality_closeout_result",
            "v35_v3x_quality_closeout_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V35_V3X_QUALITY_CLOSEOUT_REPORT.md",
            "A_SHARE_V35_LONG_HORIZON_REGRESSION_REPORT.md",
            "A_SHARE_V35_V3X_CAPABILITY_VALIDATION.md",
            "A_SHARE_V35_EXTERNAL_REVIEW_PACKAGE_REFRESH.md",
            "A_SHARE_V35_KNOWN_LIMITATIONS_REFRESH.md",
            "A_SHARE_V35_OWNER_FINAL_V3X_DASHBOARD.md",
            "A_SHARE_V35_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v34_baseline_verified",
            "v3x_release_lineage_registry_generated",
            "long_horizon_regression_evidence_generated",
            "v3x_capability_validation_generated",
            "external_review_package_refresh_generated",
            "known_limitations_refresh_generated",
            "owner_final_v3x_dashboard_generated",
            "full_regression_run",
            "full_regression_passed",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
        ],
        "required_false": [
            "fabricated_test_result",
            "fabricated_audit_result",
            "fabricated_release_evidence",
            "fabricated_capability_claim",
            "known_limitations_hidden",
            "historical_evidence_deleted",
            "audit_evidence_deleted",
            "release_evidence_deleted",
        ],
        "full_pytest_required": True,
        "warnings": [],
        "release_decision": "released_as_research_only_simulation_platform_v3x_closeout",
        "extra_result_fields": {"full_regression_mode": "split_matrix"},
        "source_result_dir": "equity_v34_portfolio_attribution",
        "source_result_name": "v34_portfolio_attribution_result",
        "source_audit_json": "a_share_v34_portfolio_attribution_audit.json",
        "regression_artifact_name": "v35_long_horizon_regression_evidence",
        "regression_seed_name": "v35_regression_seed",
    },
    {
        "key": "v36",
        "package_dir": "equity_v36_security_config_supply_chain",
        "target_version": "v3.6.0-a-share-platform-security-config-and-supply-chain-hardening",
        "source_version": "v3.5.0-a-share-v3x-quality-closeout-long-horizon-regression-and-external-review-refresh",
        "recommended_next_version": "v3.7.0-a-share-long-running-operations-observability-and-incident-drill-hardening",
        "result_name": "v36_security_config_supply_chain_result",
        "manifest_name": "v36_security_config_supply_chain_manifest",
        "audit_json": "a_share_v36_security_config_supply_chain_audit.json",
        "audit_md": "A_SHARE_V36_SECURITY_CONFIG_SUPPLY_CHAIN_AUDIT.md",
        "build_command": "build-a-share-v36-security-config-supply-chain",
        "audit_command": "audit-a-share-v36-security-config-supply-chain",
        "all_command": "build-and-audit-a-share-v36-security-config-supply-chain",
        "component_commands": [
            "build-a-share-secret-scan-review",
            "build-a-share-config-governance-review",
            "build-a-share-supply-chain-review",
            "build-a-share-filesystem-network-boundary-review",
        ],
        "json_names": [
            "v36_security_config_request",
            "v36_secret_scan_result",
            "v36_config_governance_result",
            "v36_supply_chain_dependency_result",
            "v36_filesystem_path_safety_result",
            "v36_network_boundary_result",
            "v36_owner_security_dashboard_result",
            "v36_artifact_integrity_sweep",
            "v36_protected_path_sweep",
            "v36_safety_boundary_sweep",
            "v36_security_config_supply_chain_result",
            "v36_security_config_supply_chain_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V36_SECURITY_CONFIG_OVERVIEW.md",
            "A_SHARE_V36_SECRET_SCAN_REPORT.md",
            "A_SHARE_V36_CONFIG_GOVERNANCE_REPORT.md",
            "A_SHARE_V36_SUPPLY_CHAIN_DEPENDENCY_REPORT.md",
            "A_SHARE_V36_FILESYSTEM_NETWORK_BOUNDARY_REPORT.md",
            "A_SHARE_V36_OWNER_SECURITY_DASHBOARD.md",
            "A_SHARE_V36_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v35_baseline_verified",
            "secret_scan_result_generated",
            "config_governance_result_generated",
            "supply_chain_dependency_result_generated",
            "filesystem_path_safety_result_generated",
            "network_boundary_result_generated",
            "owner_security_dashboard_generated",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
            "targeted_pytest_required",
        ],
        "required_false": [
            "high_confidence_secret_detected",
            "broker_credential_detected",
            "account_credential_detected",
            "order_api_endpoint_detected",
            "unsafe_config_override_detected",
            "unsafe_file_delete_detected",
            "broker_network_path_detected",
            "account_network_path_detected",
            "dependency_result_fabricated",
            "security_result_fabricated",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "full_pytest_deferred_until": "v4.0.0-final-maintenance-closeout",
        "warnings": [],
        "source_result_dir": "equity_v35_v3x_quality_closeout",
        "source_result_name": "v35_v3x_quality_closeout_result",
        "source_audit_json": "a_share_v35_v3x_quality_closeout_audit.json",
    },
    {
        "key": "v37",
        "package_dir": "equity_v37_operations_observability",
        "target_version": "v3.7.0-a-share-long-running-operations-observability-and-incident-drill-hardening",
        "source_version": "v3.6.0-a-share-platform-security-config-and-supply-chain-hardening",
        "recommended_next_version": "v3.8.0-a-share-data-contract-edge-case-and-market-microstructure-validation-hardening",
        "result_name": "v37_operations_observability_result",
        "manifest_name": "v37_operations_observability_manifest",
        "audit_json": "a_share_v37_operations_observability_audit.json",
        "audit_md": "A_SHARE_V37_OPERATIONS_OBSERVABILITY_AUDIT.md",
        "build_command": "build-a-share-v37-operations-observability",
        "audit_command": "audit-a-share-v37-operations-observability",
        "all_command": "build-and-audit-a-share-v37-operations-observability",
        "component_commands": [
            "build-a-share-incident-drill",
            "build-a-share-recovery-rehearsal",
            "build-a-share-owner-operations-runbook",
        ],
        "json_names": [
            "v37_operations_observability_request",
            "v37_run_telemetry_result",
            "v37_health_status_result",
            "v37_incident_drill_result",
            "v37_recovery_rehearsal_result",
            "v37_owner_operations_runbook_result",
            "v37_owner_observability_dashboard_result",
            "v37_artifact_integrity_sweep",
            "v37_protected_path_sweep",
            "v37_safety_boundary_sweep",
            "v37_operations_observability_result",
            "v37_operations_observability_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V37_OPERATIONS_OBSERVABILITY_OVERVIEW.md",
            "A_SHARE_V37_HEALTH_STATUS_REPORT.md",
            "A_SHARE_V37_INCIDENT_DRILL_REPORT.md",
            "A_SHARE_V37_RECOVERY_REHEARSAL_REPORT.md",
            "A_SHARE_V37_OWNER_OPERATIONS_RUNBOOK.md",
            "A_SHARE_V37_OWNER_OBSERVABILITY_DASHBOARD.md",
            "A_SHARE_V37_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v36_baseline_verified",
            "run_telemetry_result_generated",
            "health_status_result_generated",
            "incident_drill_result_generated",
            "recovery_rehearsal_result_generated",
            "owner_operations_runbook_generated",
            "owner_observability_dashboard_generated",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
            "targeted_pytest_required",
        ],
        "required_false": [
            "telemetry_external_notification_enabled",
            "scheduler_installed",
            "daemon_installed",
            "destructive_recovery_performed",
            "git_history_rollback_performed",
            "incident_evidence_fabricated",
            "health_status_fabricated",
            "health_score_is_owner_readiness_score",
            "health_pass_means_live_trading_ready",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "full_pytest_deferred_until": "v4.0.0-final-maintenance-closeout",
        "warnings": [],
        "source_result_dir": "equity_v36_security_config_supply_chain",
        "source_result_name": "v36_security_config_supply_chain_result",
        "source_audit_json": "a_share_v36_security_config_supply_chain_audit.json",
    },
    {
        "key": "v38",
        "package_dir": "equity_v38_data_edge_microstructure",
        "target_version": "v3.8.0-a-share-data-contract-edge-case-and-market-microstructure-validation-hardening",
        "source_version": "v3.7.0-a-share-long-running-operations-observability-and-incident-drill-hardening",
        "recommended_next_version": "v3.9.0-a-share-documentation-knowledge-base-polish-and-owner-handoff-hardening",
        "result_name": "v38_data_edge_microstructure_result",
        "manifest_name": "v38_data_edge_microstructure_manifest",
        "audit_json": "a_share_v38_data_edge_microstructure_audit.json",
        "audit_md": "A_SHARE_V38_DATA_EDGE_MICROSTRUCTURE_AUDIT.md",
        "build_command": "build-a-share-v38-data-edge-microstructure",
        "audit_command": "audit-a-share-v38-data-edge-microstructure",
        "all_command": "build-and-audit-a-share-v38-data-edge-microstructure",
        "component_commands": [
            "build-a-share-calendar-settlement-edge-review",
            "build-a-share-execution-microstructure-edge-review",
            "build-a-share-financial-pit-edge-review",
        ],
        "json_names": [
            "v38_data_edge_microstructure_request",
            "v38_calendar_edge_case_result",
            "v38_tplusone_settlement_edge_case_result",
            "v38_price_volume_constraint_edge_case_result",
            "v38_adjusted_price_corporate_action_edge_result",
            "v38_financial_pit_edge_case_result",
            "v38_execution_path_edge_case_result",
            "v38_owner_microstructure_dashboard_result",
            "v38_artifact_integrity_sweep",
            "v38_protected_path_sweep",
            "v38_safety_boundary_sweep",
            "v38_data_edge_microstructure_result",
            "v38_data_edge_microstructure_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V38_DATA_EDGE_MICROSTRUCTURE_OVERVIEW.md",
            "A_SHARE_V38_CALENDAR_SETTLEMENT_EDGE_CASES.md",
            "A_SHARE_V38_EXECUTION_MICROSTRUCTURE_EDGE_CASES.md",
            "A_SHARE_V38_ADJUSTED_PRICE_CORPORATE_ACTION_EDGE_CASES.md",
            "A_SHARE_V38_FINANCIAL_PIT_EDGE_CASES.md",
            "A_SHARE_V38_OWNER_MICROSTRUCTURE_DASHBOARD.md",
            "A_SHARE_V38_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v37_baseline_verified",
            "calendar_edge_case_result_generated",
            "tplusone_settlement_edge_case_result_generated",
            "price_volume_constraint_edge_case_result_generated",
            "adjusted_price_corporate_action_edge_result_generated",
            "financial_pit_edge_case_result_generated",
            "execution_path_edge_case_result_generated",
            "owner_microstructure_dashboard_generated",
            "account_apply_trade_bypass_absent",
            "formal_calendar_fail_closed_verified",
            "raw_adjusted_price_fallback_blocked_by_default",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
            "targeted_pytest_required",
        ],
        "required_false": [
            "calendar_edge_fabricated",
            "settlement_edge_fabricated",
            "execution_edge_fabricated",
            "financial_pit_edge_fabricated",
            "microstructure_validation_generates_trade_signal",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "full_pytest_deferred_until": "v4.0.0-final-maintenance-closeout",
        "warnings": [],
        "source_result_dir": "equity_v37_operations_observability",
        "source_result_name": "v37_operations_observability_result",
        "source_audit_json": "a_share_v37_operations_observability_audit.json",
    },
    {
        "key": "v39",
        "package_dir": "equity_v39_owner_handoff_docs",
        "target_version": "v3.9.0-a-share-documentation-knowledge-base-polish-and-owner-handoff-hardening",
        "source_version": "v3.8.0-a-share-data-contract-edge-case-and-market-microstructure-validation-hardening",
        "recommended_next_version": "v4.0.0-a-share-research-platform-final-maintenance-closeout-and-freeze",
        "result_name": "v39_owner_handoff_docs_result",
        "manifest_name": "v39_owner_handoff_docs_manifest",
        "audit_json": "a_share_v39_owner_handoff_docs_audit.json",
        "audit_md": "A_SHARE_V39_OWNER_HANDOFF_DOCS_AUDIT.md",
        "build_command": "build-a-share-v39-owner-handoff-docs",
        "audit_command": "audit-a-share-v39-owner-handoff-docs",
        "all_command": "build-and-audit-a-share-v39-owner-handoff-docs",
        "component_commands": [
            "build-a-share-final-owner-docs",
            "build-a-share-knowledge-base-polish",
            "build-a-share-owner-handoff-package",
        ],
        "json_names": [
            "v39_owner_handoff_request",
            "v39_final_documentation_result",
            "v39_knowledge_base_polish_result",
            "v39_owner_handoff_package_result",
            "v39_report_readability_consistency_result",
            "v39_owner_handoff_dashboard_result",
            "v39_artifact_integrity_sweep",
            "v39_protected_path_sweep",
            "v39_safety_boundary_sweep",
            "v39_owner_handoff_docs_result",
            "v39_owner_handoff_docs_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V39_FINAL_ARCHITECTURE_AND_CLI_GUIDE.md",
            "A_SHARE_V39_OWNER_DAILY_WORKFLOW_GUIDE.md",
            "A_SHARE_V39_KNOWLEDGE_BASE_POLISH_REPORT.md",
            "A_SHARE_V39_OWNER_HANDOFF_PACKAGE.md",
            "A_SHARE_V39_REPORT_READABILITY_CONSISTENCY.md",
            "A_SHARE_V39_OWNER_HANDOFF_DASHBOARD.md",
            "A_SHARE_V39_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v38_baseline_verified",
            "final_documentation_generated",
            "knowledge_base_polish_generated",
            "owner_handoff_package_generated",
            "report_readability_consistency_generated",
            "owner_handoff_dashboard_generated",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
            "targeted_pytest_required",
        ],
        "required_false": [
            "documentation_fabricated",
            "knowledge_base_links_fabricated",
            "handoff_includes_broker_setup",
            "handoff_includes_real_account_steps",
            "handoff_includes_trading_instruction",
            "question_router_generates_trading_advice",
            "forbidden_wording_detected",
            "full_pytest_run",
        ],
        "full_pytest_required": False,
        "full_pytest_deferred_until": "v4.0.0-final-maintenance-closeout",
        "warnings": [],
        "source_result_dir": "equity_v38_data_edge_microstructure",
        "source_result_name": "v38_data_edge_microstructure_result",
        "source_audit_json": "a_share_v38_data_edge_microstructure_audit.json",
    },
    {
        "key": "v40",
        "package_dir": "equity_v40_final_maintenance_closeout",
        "target_version": "v4.0.0-a-share-research-platform-final-maintenance-closeout-and-freeze",
        "source_version": "v3.9.0-a-share-documentation-knowledge-base-polish-and-owner-handoff-hardening",
        "recommended_next_version": "maintenance-only",
        "result_name": "v40_final_maintenance_closeout_result",
        "manifest_name": "v40_final_maintenance_closeout_manifest",
        "audit_json": "a_share_v40_final_maintenance_closeout_audit.json",
        "audit_md": "A_SHARE_V40_FINAL_MAINTENANCE_CLOSEOUT_AUDIT.md",
        "build_command": "build-a-share-v40-final-maintenance-closeout",
        "audit_command": "audit-a-share-v40-final-maintenance-closeout",
        "all_command": "build-and-audit-a-share-v40-final-maintenance-closeout",
        "component_commands": [
            "build-a-share-v40-final-regression-evidence",
            "build-a-share-v40-final-freeze-package",
            "build-a-share-v40-owner-final-maintenance-dashboard",
        ],
        "json_names": [
            "v40_final_maintenance_closeout_request",
            "v40_final_release_lineage_registry",
            "v40_final_regression_evidence",
            "v40_security_ops_data_docs_validation_result",
            "v40_external_reviewer_freeze_package_result",
            "v40_known_limitations_final_result",
            "v40_owner_final_maintenance_dashboard_result",
            "v40_release_health_report",
            "v40_artifact_integrity_sweep",
            "v40_protected_path_sweep",
            "v40_safety_boundary_sweep",
            "v40_final_maintenance_closeout_result",
            "v40_final_maintenance_closeout_manifest",
        ],
        "markdown_names": [
            "A_SHARE_V40_FINAL_MAINTENANCE_CLOSEOUT_REPORT.md",
            "A_SHARE_V40_FINAL_REGRESSION_EVIDENCE.md",
            "A_SHARE_V40_SECURITY_OPS_DATA_DOCS_VALIDATION.md",
            "A_SHARE_V40_EXTERNAL_REVIEWER_FREEZE_PACKAGE.md",
            "A_SHARE_V40_KNOWN_LIMITATIONS_FINAL.md",
            "A_SHARE_V40_OWNER_FINAL_MAINTENANCE_DASHBOARD.md",
            "A_SHARE_V40_SAFETY_AND_LIMITATIONS.md",
        ],
        "required_true": [
            "v39_baseline_verified",
            "final_release_lineage_registry_generated",
            "final_regression_evidence_generated",
            "security_ops_data_docs_validation_generated",
            "external_reviewer_freeze_package_generated",
            "known_limitations_final_generated",
            "owner_final_maintenance_dashboard_generated",
            "release_health_report_generated",
            "full_regression_run",
            "full_regression_passed",
            "artifact_integrity_sweep_passed",
            "protected_path_sweep_passed",
            "safety_boundary_sweep_passed",
        ],
        "required_false": [
            "fabricated_test_result",
            "fabricated_audit_result",
            "fabricated_release_evidence",
            "fabricated_security_evidence",
            "fabricated_incident_evidence",
            "fabricated_docs_evidence",
            "known_limitations_hidden",
            "historical_evidence_deleted",
            "audit_evidence_deleted",
            "release_evidence_deleted",
        ],
        "full_pytest_required": True,
        "warnings": [],
        "freeze_decision": "frozen_as_research_only_simulation_platform",
        "extra_result_fields": {"full_regression_mode": "split_matrix"},
        "source_result_dir": "equity_v39_owner_handoff_docs",
        "source_result_name": "v39_owner_handoff_docs_result",
        "source_audit_json": "a_share_v39_owner_handoff_docs_audit.json",
        "regression_artifact_name": "v40_final_regression_evidence",
        "regression_seed_name": "v40_regression_seed",
    },
]


def spec_by_key(key: str) -> dict[str, Any]:
    for spec in RELEASE_SPECS:
        if spec["key"] == key:
            return spec
    raise KeyError(key)


def command_to_spec(command: str) -> tuple[dict[str, Any], str] | tuple[None, None]:
    for spec in RELEASE_SPECS:
        if command == spec["build_command"]:
            return spec, "build"
        if command == spec["audit_command"]:
            return spec, "audit"
        if command == spec["all_command"]:
            return spec, "all"
        if command in spec["component_commands"]:
            return spec, "component"
    return None, None
