"""Catalog of external repositories for v0.7 intake."""

from __future__ import annotations

from typing import Any


PROJECTS: list[dict[str, Any]] = [
    {
        "repo_name": "AlphaSift",
        "github_url": "https://github.com/ZhuLinsen/alphasift.git",
        "local_dir": "alphasift",
        "project_focus": "full-market scanning, multi-factor candidate ranking, risk-aware scoring, saved-run evaluation",
        "usable_modules": ["README.md", "src/", "examples/", "configs/", "strategies/", "reports/", "evaluation/"],
        "reusable_design_patterns": ["full-market scanner", "hard filters", "factor scoring", "candidate ranking schema", "T+N evaluation schema", "saved run artifacts"],
        "integration_priority": "A",
        "integration_risk": "medium",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Use as immediate design reference for scanner, ranking, and saved-run artifacts; do not allow LLM output to authorize trades.",
    },
    {
        "repo_name": "qstock",
        "github_url": "https://github.com/tkfy920/qstock.git",
        "local_dir": "qstock",
        "project_focus": "A-share public data adapters, WenCai-style screening, RPS, MM trend, fundamentals, capital flow, visualization",
        "usable_modules": ["README.md", "qstock/", "qstock/data/", "qstock/stock/", "qstock/backtest/", "qstock/plot/"],
        "reusable_design_patterns": ["data adapter", "public screening condition expression", "RPS indicator", "MM trend model", "fundamental fields", "capital flow fields"],
        "integration_priority": "A",
        "integration_risk": "medium_high",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Use as data and factor-design reference; keep trading-core local persistence, hash, and coverage audit rules.",
    },
    {
        "repo_name": "daily_stock_analysis",
        "github_url": "https://github.com/ZhuLinsen/daily_stock_analysis.git",
        "local_dir": "daily_stock_analysis",
        "project_focus": "daily stock analysis reports, LLM summaries, market/news organization, notification ideas",
        "usable_modules": ["README.md", "docs/", "reports/", "main.py", "analysis/", "notification/"],
        "reusable_design_patterns": ["daily briefing structure", "LLM report prompt", "multi-market report layout", "notification workflow", "news risk note"],
        "integration_priority": "A",
        "integration_risk": "medium",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Use as owner-readable Chinese daily briefing reference; require local evidence chain for claims.",
    },
    {
        "repo_name": "guiwzh/stock",
        "github_url": "https://github.com/guiwzh/stock.git",
        "local_dir": "stock",
        "project_focus": "A-share stock scoring assistant with short/long score weighting and value/technical/valuation dimensions",
        "usable_modules": ["README.md", "src/", "config/", "strategy/"],
        "reusable_design_patterns": ["short score weights", "long score weights", "value/technical/valuation scoring", "readable stock score report"],
        "integration_priority": "A",
        "integration_risk": "medium",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Use as scoring-weight reference and extend into LongScore, MidScore, ShortScore, RiskScore, LiquidityScore, and CompositeOpportunityScore.",
    },
    {
        "repo_name": "Qlib",
        "github_url": "https://github.com/microsoft/qlib.git",
        "local_dir": "qlib",
        "project_focus": "ML quant research workflow, dataset split, model evaluation, RankIC/IC, portfolio evaluation",
        "usable_modules": ["README.md", "examples/", "qlib/contrib/", "qlib/workflow/", "qlib/backtest/", "qlib/model/"],
        "reusable_design_patterns": ["dataset split", "model training workflow", "backtest evaluation metrics", "RankIC/IC evaluation", "portfolio analysis report", "experiment tracking"],
        "integration_priority": "B",
        "integration_risk": "high",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Use for ML and walk-forward evaluation design only; do not pull heavy framework dependencies into v0.7 main flow.",
    },
    {
        "repo_name": "AlphaEvo",
        "github_url": "https://github.com/ZhuLinsen/alphaevo.git",
        "local_dir": "alphaevo",
        "project_focus": "strategy weight mutation, controlled optimization, evolution report, failed strategy diagnosis",
        "usable_modules": ["README.md", "strategies/", "evolution/", "backtest/", "reports/"],
        "reusable_design_patterns": ["controlled mutation", "scoring weight optimization", "strategy evolution report", "parameter evidence chain", "failed strategy diagnosis"],
        "integration_priority": "B",
        "integration_risk": "medium_high",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Use only for research on Long/Mid/ShortScore weights; require walk-forward validation and never allow automatic trading.",
    },
    {
        "repo_name": "zvt",
        "github_url": "https://github.com/zvtvz/zvt.git",
        "local_dir": "zvt",
        "project_focus": "market data, factor, and quant research framework reference",
        "usable_modules": ["README.md", "src/", "zvt/", "examples/"],
        "reusable_design_patterns": ["data domain modeling", "factor pipeline", "research framework organization"],
        "integration_priority": "B/C",
        "integration_risk": "high",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Keep as optional architecture reference; do not import into v0.7 main flow without separate dependency and license review.",
        "optional": True,
    },
    {
        "repo_name": "easytrader",
        "github_url": "https://github.com/shidenggui/easytrader.git",
        "local_dir": "easytrader",
        "project_focus": "broker/client adapter reference, miniQMT, Xueqiu portfolio, future order-submit layering",
        "usable_modules": ["README.md", "easytrader/", "easytrader/clienttrader.py", "easytrader/miniqmt_trader.py", "easytrader/xqtrader.py"],
        "reusable_design_patterns": ["broker adapter interface", "miniQMT adapter", "client automation separation", "order preview to submit layering", "read-only account sync"],
        "integration_priority": "D",
        "integration_risk": "high",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Use only for future adapter research; v0.7 must not submit orders or manage credentials.",
    },
    {
        "repo_name": "easyquotation",
        "github_url": "https://github.com/shidenggui/easyquotation.git",
        "local_dir": "easyquotation",
        "project_focus": "free quote adapters and quote normalization reference",
        "usable_modules": ["README.md", "easyquotation/"],
        "reusable_design_patterns": ["quote adapter", "quote normalization", "watchlist polling", "field standardization"],
        "integration_priority": "D",
        "integration_risk": "medium_high",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Use as future quote adapter reference; do not feed real-time quotes into formal v0.7 scoring by default.",
    },
    {
        "repo_name": "easyquant",
        "github_url": "https://github.com/shidenggui/easyquant.git",
        "local_dir": "easyquant",
        "project_focus": "event engine and quotation/trader layering reference",
        "usable_modules": ["README.md", "easyquant/"],
        "reusable_design_patterns": ["event engine", "quotation/trader separation", "strategy event loop", "simulated trading flow"],
        "integration_priority": "D",
        "integration_risk": "high",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Use only as future event-engine and adapter reference; do not connect trading code in v0.7.",
    },
    {
        "repo_name": "THSTrader",
        "github_url": "https://github.com/nladuo/THSTrader.git",
        "local_dir": "THSTrader",
        "project_focus": "Tonghuashun simulated trading automation research",
        "usable_modules": ["README.md", "trader/", "examples/"],
        "reusable_design_patterns": ["THS simulated trading flow", "Android emulator/app automation", "simulated order submit adapter"],
        "integration_priority": "D",
        "integration_risk": "high",
        "requires_manual_review": True,
        "can_import_directly": False,
        "recommended_action": "Keep outside main flow as experimental_ths_sim_adapter research only.",
    },
]
